Add Python version check.
Before:

    $ python2.5 unligature.py
      File "unligature.py", line 47
        print('Warning: U+%(code)s (%(name)s) is not supported' % locals(), file=sys.stderr)
                                                                                ^
    SyntaxError: invalid syntax

After:

    $ python2.5 unligature.py
      File "unligature.py", line 21
        b''  # Python >= 2.6 is required
          ^
    SyntaxError: invalid syntax