Add check against Python 3.X.
Before:

    $ python3 unligature.py < /usr/share/unicode/UnicodeData.txt > unligature.l
    Traceback (most recent call last):
      File "unligature.py", line 97, in <module>
        main()
      File "unligature.py", line 93, in main
        read_unicode_data(sys.stdin, categories)
      File "unligature.py", line 38, in read_unicode_data
        for category, ligature_dict in categories.iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'

After:

    $ python3 unligature.py < /usr/share/unicode/UnicodeData.txt > unligature.l
      File "unligature.py", line 22
        exec ''  # Python 2.X is required
              ^
    SyntaxError: Missing parentheses in call to 'exec'